### ISSUE TITLE
Causing conflict on WP dashboard

### ISSUE THREAD

**Issue by vegasgeek** [jtsternberg/Code-Snippets-CPT#23]
When CodeSnippets CPT is active, if you are on the main WP dashboard page, the WP menu fly-outs no longer work. If you go to secondary pages, they work just fine.

**Comment by jtsternberg** [comment]
Hmm I can't duplicate this issue. It may be a conflict with another plugin?

Here'a gif of it working normally for me: http://b.ustin.co/13Gsn

I think #24 is related, but I don't want to accept that PR because it will disable the functionality that you see in that gif.

Is there any other info you can provide?

**Comment by jtsternberg** [comment]
This is probably the reason: https://github.com/jtsternberg/Code-Snippets-CPT/pull/24#issuecomment-217444384

**Comment by vegasgeek** [comment]
Yup. Same reason. I'll mark this closed. thanks!
